* Day 2: Password Philosophy

https://adventofcode.com/2020/day/2/

** Part 1

*** Problem

Your flight departs in a few days from the coastal airport; the easiest way down to the coast from here is via toboggan.

The shopkeeper at the North Pole Toboggan Rental Shop is having a bad day. "Something's wrong with our computers; we can't log in!" You ask if you can take a look.

Their password database seems to be a little corrupted: some of the passwords wouldn't have been allowed by the Official Toboggan Corporate Policy that was in effect when they were chosen.

To try to debug the problem, they have created a list (your puzzle input) of passwords (according to the corrupted database) and the corporate policy when that password was set.

For example, suppose you have the following list:

#+begin_src text
1-3 a: abcde
1-3 b: cdefg
2-9 c: ccccccccc
#+end_src

Each line gives the password policy and then the password. The password policy indicates the lowest and highest number of times a given letter must appear for the password to be valid. For example, 1-3 a means that the password must contain a at least 1 time and at most 3 times.

In the above example, 2 passwords are valid. The middle password, cdefg, is not; it contains no instances of b, but needs at least 1. The first and third passwords are valid: they contain one a or nine c, both within the limits of their respective policies.

*How many passwords are valid* according to their policies?

*** Solution

#+begin_src C++ :includes '(<vector> <numeric> <iostream> <map>) :namespaces std :flags -std=c++11 :results verbatim
  #include <iostream>
  #include <fstream>
  #include <vector>
  #include <algorithm>
  using namespace std;

  bool isValidPassword(int min, int max, char letter, const string& password) {
      int letterCount = 0;

      for (auto c : password) {
          if (c == letter) {
              ++letterCount;

              if (letterCount > max)
                  return false;
          }
      }

      return min <= letterCount && letterCount <= max;
  }

  int main() {
      ifstream file("input");
      int min;
      int max;
      char ignoredChar;
      char letter;
      string password;

      int validCount = 0;

      while (file >> min >> ignoredChar >> max >> letter >> ignoredChar >> password) {
          // cout << min << " " << max << " " << letter << " " << password << " ";

          if(isValidPassword(min, max, letter, password)) {
              // cout << "valid\n";
              ++validCount;
          } else {
              // cout << "invalid\n";
          }
      }

      file.close();
      cout << validCount << "\n";
  }
#+end_src

#+RESULTS:
: 660

**** Output

#+begin_src text
660
#+end_src

** Part 2

*** Problem

While it appears you validated the passwords correctly, they don't seem to be what the Official Toboggan Corporate Authentication System is expecting.

The shopkeeper suddenly realizes that he just accidentally explained the password policy rules from his old job at the sled rental place down the street! The Official Toboggan Corporate Policy actually works a little differently.

Each policy actually describes two *positions in the password*, where 1 means the first character, 2 means the second character, and so on. (Be careful; Toboggan Corporate Policies have no concept of "index zero"!) Exactly one of these positions must contain the given letter. Other occurrences of the letter are irrelevant for the purposes of policy enforcement.

Given the same example list from above:

- ~1-3 a: abcde~ is *valid*: position 1 contains a and position 3 does not.
- ~1-3 b: cdefg~ is *invalid*: neither position 1 nor position 3 contains b.
- ~2-9 c: ccccccccc~ is *invalid*: both position 2 and position 9 contain c.

*How many passwords are valid* according to the new interpretation of the policies?

*** Solution

#+begin_src C++ :includes '(<vector> <numeric> <iostream> <map>) :namespaces std :flags -std=c++11 :results verbatim
  #include <iostream>
  #include <fstream>
  #include <vector>
  #include <algorithm>
  using namespace std;

  bool isValidPassword(int i, int j, char letter, const string& password) {
      return (password[i-1] == letter && password[j-1] != letter) ||
             (password[i-1] != letter && password[j-1] == letter);
  }

  int main() {
      ifstream file("input");
      int i;
      int j;
      char ignoredChar;
      char letter;
      string password;

      int validCount = 0;

      while (file >> i >> ignoredChar >> j >> letter >> ignoredChar >> password) {
          // cout << i << " " << j << " " << letter << " " << password << " ";

          if(isValidPassword(i, j, letter, password)) {
              // cout << "valid\n";
              ++validCount;
          } else {
              // cout << "invalid\n";
          }
      }

      file.close();
      cout << validCount << "\n";
  }
#+end_src

#+RESULTS:
: 530

**** Output

#+begin_src text
530
#+end_src
